"""TwinOps AI - Agent Prompts"""
from .agent_prompts import (
    SUPERVISOR_SYSTEM_PROMPT,
    IDENTITY_HISTORY_SYSTEM_PROMPT,
    SENSOR_ANALYSIS_SYSTEM_PROMPT,
    ENVIRONMENTAL_RISK_SYSTEM_PROMPT,
    PREDICTIVE_MAINTENANCE_SYSTEM_PROMPT,
    SAFETY_SYSTEM_PROMPT,
    REPORT_SYSTEM_PROMPT,
)

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "IDENTITY_HISTORY_SYSTEM_PROMPT",
    "SENSOR_ANALYSIS_SYSTEM_PROMPT",
    "ENVIRONMENTAL_RISK_SYSTEM_PROMPT",
    "PREDICTIVE_MAINTENANCE_SYSTEM_PROMPT",
    "SAFETY_SYSTEM_PROMPT",
    "REPORT_SYSTEM_PROMPT",
]
